all:
	g++ -fopenmp -o asp.exe asp.c
	g++ -fopenmp -o bp.exe bp.c
	g++ -fopenmp -o drc.exe drc.c
	g++ -fopenmp -o flag.exe flag.c
	g++ -fopenmp -o nf.exe nf.c
	g++ -fopenmp -o of.exe of.c
	g++ -fopenmp -o pm.exe pm.c
