all:
	g++ -fopenmp ft.c -o ft
	g++ -fopenmp orphan.c -o orphan
	g++ -fopenmp stfv.c -o stfv
	g++ -fopenmp taskgroup.c -o taskgroup
	g++ -fopenmp taskwait.c -o taskwait
	g++ -fopenmp taskyield.c -o taskyield
	g++ -fopenmp tei.c -o tei
	g++ -fopenmp tgp.c -o tgp
	g++ -fopenmp tied.c -o tied
	g++ -fopenmp tn.c -o tn
	g++ -fopenmp tp.c -o tp
	g++ -fopenmp tps.c -o tps
	g++ -fopenmp ts.c -o ts	
	g++ -fopenmp tst.c -o tst
	g++ -fopenmp tsst.c -o tsst		
	