all:
	g++ -fopenmp -o dfapli.exe dfapli.c
	g++ -fopenmp -o fap.exe fap.c
	g++ -fopenmp -o fc.exe fc.c
	g++ -fopenmp -o fs.exe fs.c
	g++ -fopenmp -o fsd.exe fsd.c
	g++ -fopenmp -o fss.exe fss.c
	g++ -fopenmp -o ost.exe ost.c
